language: python

python: 3.5

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c "CREATE USER vero4ka WITH PASSWORD 'secret' SUPERUSER;" -U postgres
  - psql -c "CREATE database desparchado_test  OWNER vero4ka;" -U postgres
  - psql -c "create extension postgis" desparchado_test

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - python manage.py test
  - coverage run manage.py test


